// Country → State → City cascading location data
// Focused on India (all states & UTs) + major global job markets

export const LOCATION_DATA: Record<string, Record<string, string[]>> = {
  India: {
    "Andhra Pradesh": [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Tirupati",
      "Nellore",
      "Kakinada",
      "Rajahmundry",
      "Kurnool",
      "Anantapur",
    ],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
    Assam: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tezpur",
      "Tinsukia",
    ],
    Bihar: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Darbhanga",
      "Purnia",
      "Arrah",
    ],
    Chhattisgarh: [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Durg",
      "Korba",
      "Rajnandgaon",
    ],
    Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
    Gujarat: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Gandhinagar",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Anand",
      "Morbi",
    ],
    Haryana: [
      "Gurugram",
      "Faridabad",
      "Panipat",
      "Ambala",
      "Karnal",
      "Hisar",
      "Rohtak",
      "Sonipat",
    ],
    "Himachal Pradesh": [
      "Shimla",
      "Dharamshala",
      "Mandi",
      "Solan",
      "Kullu",
      "Manali",
      "Bilaspur",
    ],
    Jharkhand: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Hazaribagh",
      "Deoghar",
    ],
    Karnataka: [
      "Bangalore",
      "Mysore",
      "Hubli",
      "Mangalore",
      "Belgaum",
      "Gulbarga",
      "Davangere",
      "Shimoga",
      "Udupi",
    ],
    Kerala: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Kannur",
      "Alappuzha",
      "Palakkad",
      "Malappuram",
    ],
    "Madhya Pradesh": [
      "Bhopal",
      "Indore",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Rewa",
    ],
    Maharashtra: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Aurangabad",
      "Thane",
      "Navi Mumbai",
      "Solapur",
      "Kolhapur",
      "Amravati",
    ],
    Manipur: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
    Meghalaya: ["Shillong", "Tura", "Jowai", "Nongstoin"],
    Mizoram: ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
    Nagaland: ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
    Odisha: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Balasore",
    ],
    Punjab: [
      "Chandigarh",
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
    ],
    Rajasthan: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Bhilwara",
    ],
    Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
    "Tamil Nadu": [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Vellore",
      "Thoothukudi",
    ],
    Telangana: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Khammam",
      "Secunderabad",
    ],
    Tripura: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
    "Uttar Pradesh": [
      "Lucknow",
      "Noida",
      "Ghaziabad",
      "Kanpur",
      "Agra",
      "Varanasi",
      "Meerut",
      "Allahabad",
      "Greater Noida",
      "Bareilly",
    ],
    Uttarakhand: [
      "Dehradun",
      "Haridwar",
      "Rishikesh",
      "Haldwani",
      "Roorkee",
      "Nainital",
    ],
    "West Bengal": [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Bardhaman",
      "Kalyani",
    ],
    // Union Territories
    "Andaman and Nicobar Islands": ["Port Blair"],
    Chandigarh: ["Chandigarh"],
    "Dadra and Nagar Haveli and Daman and Diu": [
      "Silvassa",
      "Daman",
      "Diu",
    ],
    Delhi: [
      "New Delhi",
      "Delhi",
      "Dwarka",
      "Rohini",
      "Saket",
      "Noida (NCR)",
      "Gurugram (NCR)",
    ],
    "Jammu and Kashmir": [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Udhampur",
    ],
    Ladakh: ["Leh", "Kargil"],
    Lakshadweep: ["Kavaratti"],
    Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  },

  "United States": {
    California: [
      "San Francisco",
      "Los Angeles",
      "San Jose",
      "San Diego",
      "Sacramento",
      "Oakland",
      "Irvine",
      "Palo Alto",
      "Mountain View",
    ],
    "New York": [
      "New York City",
      "Buffalo",
      "Rochester",
      "Albany",
      "Syracuse",
    ],
    Texas: [
      "Austin",
      "Dallas",
      "Houston",
      "San Antonio",
      "Fort Worth",
      "Plano",
    ],
    Washington: ["Seattle", "Bellevue", "Redmond", "Tacoma", "Spokane"],
    Massachusetts: ["Boston", "Cambridge", "Worcester", "Springfield"],
    Illinois: ["Chicago", "Aurora", "Naperville", "Rockford"],
    Georgia: ["Atlanta", "Savannah", "Augusta", "Columbus"],
    Colorado: ["Denver", "Boulder", "Colorado Springs", "Aurora"],
    Virginia: ["Arlington", "Richmond", "Reston", "McLean", "Norfolk"],
    "North Carolina": [
      "Charlotte",
      "Raleigh",
      "Durham",
      "Greensboro",
      "Asheville",
    ],
    Pennsylvania: ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown"],
    Florida: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"],
    Michigan: ["Detroit", "Ann Arbor", "Grand Rapids", "Lansing"],
    Ohio: ["Columbus", "Cleveland", "Cincinnati", "Dayton"],
    Oregon: ["Portland", "Salem", "Eugene", "Bend"],
    Arizona: ["Phoenix", "Scottsdale", "Tucson", "Mesa"],
    "New Jersey": ["Newark", "Jersey City", "Princeton", "Hoboken"],
    Maryland: ["Baltimore", "Bethesda", "Rockville", "Columbia"],
    Minnesota: ["Minneapolis", "Saint Paul", "Rochester", "Bloomington"],
    Connecticut: ["Hartford", "New Haven", "Stamford", "Bridgeport"],
    Utah: ["Salt Lake City", "Provo", "Lehi", "Ogden"],
  },

  "United Kingdom": {
    England: [
      "London",
      "Manchester",
      "Birmingham",
      "Leeds",
      "Bristol",
      "Liverpool",
      "Cambridge",
      "Oxford",
      "Reading",
      "Brighton",
    ],
    Scotland: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
    Wales: ["Cardiff", "Swansea", "Newport", "Bangor"],
    "Northern Ireland": ["Belfast", "Derry", "Lisburn"],
  },

  Canada: {
    Ontario: [
      "Toronto",
      "Ottawa",
      "Mississauga",
      "Hamilton",
      "Waterloo",
      "Kitchener",
      "London",
    ],
    "British Columbia": [
      "Vancouver",
      "Victoria",
      "Burnaby",
      "Surrey",
      "Kelowna",
    ],
    Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau"],
    Alberta: ["Calgary", "Edmonton", "Red Deer", "Lethbridge"],
    Manitoba: ["Winnipeg", "Brandon"],
    Saskatchewan: ["Saskatoon", "Regina"],
    "Nova Scotia": ["Halifax", "Sydney"],
    "New Brunswick": ["Fredericton", "Saint John", "Moncton"],
  },

  Australia: {
    "New South Wales": [
      "Sydney",
      "Newcastle",
      "Wollongong",
      "Central Coast",
    ],
    Victoria: ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
    Queensland: ["Brisbane", "Gold Coast", "Cairns", "Townsville"],
    "Western Australia": ["Perth", "Fremantle", "Bunbury"],
    "South Australia": ["Adelaide", "Mount Gambier"],
    Tasmania: ["Hobart", "Launceston"],
    "Australian Capital Territory": ["Canberra"],
    "Northern Territory": ["Darwin", "Alice Springs"],
  },

  Germany: {
    Bavaria: ["Munich", "Nuremberg", "Augsburg", "Regensburg"],
    "North Rhine-Westphalia": [
      "Cologne",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Bonn",
    ],
    "Baden-Württemberg": [
      "Stuttgart",
      "Heidelberg",
      "Karlsruhe",
      "Mannheim",
      "Freiburg",
    ],
    Berlin: ["Berlin"],
    Hamburg: ["Hamburg"],
    Hesse: ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel"],
    "Lower Saxony": ["Hanover", "Brunswick", "Göttingen", "Oldenburg"],
    Saxony: ["Dresden", "Leipzig", "Chemnitz"],
  },

  "United Arab Emirates": {
    Dubai: ["Dubai", "Jebel Ali", "Dubai Marina", "Business Bay"],
    "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Khalifa City"],
    Sharjah: ["Sharjah"],
    Ajman: ["Ajman"],
    "Ras Al Khaimah": ["Ras Al Khaimah"],
    Fujairah: ["Fujairah"],
    "Umm Al Quwain": ["Umm Al Quwain"],
  },

  Singapore: {
    Central: [
      "Downtown Core",
      "Marina Bay",
      "Orchard",
      "Raffles Place",
      "Tanjong Pagar",
    ],
    East: ["Tampines", "Bedok", "Changi", "Pasir Ris"],
    West: ["Jurong East", "Clementi", "Buona Vista"],
    North: ["Woodlands", "Yishun", "Sembawang"],
    "North-East": ["Sengkang", "Punggol", "Hougang"],
  },

  Japan: {
    "Tokyo Metropolis": [
      "Tokyo",
      "Shibuya",
      "Shinjuku",
      "Minato",
      "Chiyoda",
    ],
    Osaka: ["Osaka", "Sakai"],
    Kanagawa: ["Yokohama", "Kawasaki"],
    Aichi: ["Nagoya", "Toyota"],
    Fukuoka: ["Fukuoka", "Kitakyushu"],
    Kyoto: ["Kyoto"],
    Hyogo: ["Kobe"],
  },

  "South Korea": {
    Seoul: ["Seoul", "Gangnam", "Mapo"],
    Gyeonggi: ["Suwon", "Seongnam", "Incheon", "Bundang"],
    Busan: ["Busan"],
    Daejeon: ["Daejeon"],
    Daegu: ["Daegu"],
    Jeju: ["Jeju City"],
  },

  Netherlands: {
    "North Holland": ["Amsterdam", "Haarlem"],
    "South Holland": ["Rotterdam", "The Hague", "Leiden"],
    Utrecht: ["Utrecht"],
    "North Brabant": ["Eindhoven", "Tilburg", "Breda"],
    Gelderland: ["Arnhem", "Nijmegen"],
    Groningen: ["Groningen"],
  },

  Ireland: {
    Leinster: ["Dublin", "Kilkenny", "Drogheda"],
    Munster: ["Cork", "Limerick", "Waterford", "Galway"],
    Connacht: ["Galway", "Sligo"],
    Ulster: ["Belfast", "Derry"],
  },

  France: {
    "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt"],
    "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne"],
    "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon"],
    Occitanie: ["Toulouse", "Montpellier", "Nîmes"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges"],
    "Hauts-de-France": ["Lille", "Amiens"],
  },
};

/** Returns sorted list of country names */
export function getCountries(): string[] {
  return Object.keys(LOCATION_DATA).sort();
}

/** Returns sorted list of states for a given country */
export function getStates(country: string): string[] {
  return Object.keys(LOCATION_DATA[country] ?? {}).sort();
}

/** Returns sorted list of cities for a given country and state */
export function getCities(country: string, state: string): string[] {
  return (LOCATION_DATA[country]?.[state] ?? []).sort();
}
