export const roadmapStages = [
  {
    id: "1",
    title: "Discover interests",
    description: "Clarify what you enjoy and what careers align with your values.",
    timeRange: "1–2 weeks",
    status: "completed" as const,
    actions: [
      "Complete the career quiz",
      "Review recommended career clusters",
      "Note your top 3 interests",
    ],
    resourceIds: ["quiz"],
  },
  {
    id: "2",
    title: "Learn fundamentals",
    description: "Build core knowledge and skills for your chosen path.",
    timeRange: "1–3 months",
    status: "in_progress" as const,
    actions: [
      "Pick 2–3 courses from Learning Resources",
      "Set a weekly study goal",
      "Join a relevant community or forum",
    ],
    resourceIds: [],
  },
  {
    id: "3",
    title: "Build portfolio",
    description: "Showcase projects and evidence of your skills.",
    timeRange: "2–4 months",
    status: "not_started" as const,
    actions: [
      "Create a portfolio site or GitHub profile",
      "Complete 1–2 portfolio projects",
      "Get feedback from peers or mentors",
    ],
    resourceIds: [],
  },
  {
    id: "4",
    title: "Network & job search",
    description: "Connect with people and find opportunities.",
    timeRange: "Ongoing",
    status: "not_started" as const,
    actions: [
      "Optimize LinkedIn and resume",
      "Apply to 5–10 roles per week",
      "Reach out to 2 people in your target field",
    ],
    resourceIds: [],
  },
  {
    id: "5",
    title: "Apply and interview",
    description: "Prepare for and ace interviews.",
    timeRange: "1–2 months",
    status: "not_started" as const,
    actions: [
      "Practice common interview questions",
      "Use the Analyze tool for resume and JD feedback",
      "Schedule mock interviews",
    ],
    resourceIds: [],
  },
];

export const learningResources = [
  {
    id: "1",
    title: "Introduction to Programming",
    type: "course" as const,
    description: "Learn variables, loops, and functions in Python.",
    durationMinutes: 600,
    level: "Beginner" as const,
    source: "Coursera",
    url: "#",
  },
  {
    id: "2",
    title: "Data Structures and Algorithms",
    type: "course" as const,
    description: "Arrays, linked lists, trees, and sorting.",
    durationMinutes: 1200,
    level: "Intermediate" as const,
    source: "edX",
    url: "#",
  },
  {
    id: "3",
    title: "How to Write a Tech Resume",
    type: "article" as const,
    description: "Action verbs and bullet structure that get callbacks.",
    durationMinutes: 15,
    level: "Beginner" as const,
    source: "Blog",
    url: "#",
  },
  {
    id: "4",
    title: "System Design Basics",
    type: "video" as const,
    description: "Scaling, load balancing, and databases.",
    durationMinutes: 90,
    level: "Advanced" as const,
    source: "YouTube",
    url: "#",
  },
  {
    id: "5",
    title: "Frontend Bootcamp",
    type: "bootcamp" as const,
    description: "HTML, CSS, JavaScript, and React in 12 weeks.",
    durationMinutes: 10080,
    level: "Beginner" as const,
    source: "Bootcamp.io",
    url: "#",
  },
];

export const savedJobs = [
  {
    id: "1",
    title: "Junior Frontend Developer",
    company: "TechCorp Inc",
    location: "Remote",
    status: "applied" as const,
    updatedAt: "2025-02-20",
    url: "#",
  },
  {
    id: "2",
    title: "Software Engineer I",
    company: "StartupXYZ",
    location: "Hybrid · NYC",
    status: "interviewing" as const,
    updatedAt: "2025-02-22",
    url: "#",
  },
  {
    id: "3",
    title: "Full Stack Developer",
    company: "BigCo",
    location: "On-site · SF",
    status: "saved" as const,
    updatedAt: "2025-02-18",
    url: "#",
  },
];

export const careerQuizResults = [
  {
    id: "se",
    title: "Software Engineering",
    summary: "Design, build, and maintain software systems.",
    salaryMin: 70000,
    salaryMax: 150000,
    education: "Bachelor's in CS or related",
    skills: ["Programming", "Problem solving", "Collaboration"],
  },
  {
    id: "da",
    title: "Data Analytics",
    summary: "Turn data into insights for business decisions.",
    salaryMin: 60000,
    salaryMax: 120000,
    education: "Bachelor's or Master's in STEM",
    skills: ["SQL", "Statistics", "Visualization"],
  },
  {
    id: "pm",
    title: "Product Management",
    summary: "Define and ship products users love.",
    salaryMin: 80000,
    salaryMax: 160000,
    education: "Bachelor's + experience",
    skills: ["Communication", "Prioritization", "User research"],
  },
];

export const colleges = [
  {
    id: "1",
    name: "State Tech University",
    location: "California, USA",
    degree: "Bachelor's in Computer Science",
    costRange: "$12k – $18k/year",
    admissionRate: "42%",
    strengths: ["Strong co-op program", "Industry partnerships", "Diverse campus"],
  },
  {
    id: "2",
    name: "Global Business School",
    location: "New York, USA",
    degree: "MBA",
    costRange: "$45k – $55k/year",
    admissionRate: "28%",
    strengths: ["Top-ranked MBA", "Alumni network", "Finance focus"],
  },
];
